

#
#appName= control
#appPackName= com.tool.control
#
#versionCode= 2024030501
#versionName=1.0.0
#
#
#storeFile= remote.jks
#keyAlias= remote
#keyPassword= xmsjremote




AES_KEY=5eYKK6y12IngV5QA

AES_SECRET=d8f3218f173139d9ef4e45b875008afd


